### ISSUE TITLE
Possible to encode for BigGAN-512?

### ISSUE THREAD

**Issue by wolfgangmeyers** [disanda/MTV-TSA#1]
I notice there is an encoder for BigGAN-256, would it be possible to train an encoder for the 512 size?

**Comment by disanda** [comment]
Yes, it can do this.

(1) download 512 pre-trained model of BigGAN:
https://tfhub.dev/deepmind/biggan-deep-512/1

(2) choose a file: [E_align.py](https://github.com/disanda/MTV-TSA/blob/master/E_align.py) or [E_mis_align.py](https://github.com/disanda/MTV-TSA/blob/master/E_mis_align.py)

then, modified the parameters:  a. img_size = 512,   b. config_dir = 'your path of pre-trained biggan-512' ,  c. mtype = 4
The parameters is at the end of the file, as below:

if __name__ == "__main__": 

    parser = argparse.ArgumentParser(description='the training args')
    parser.add_argument('--iterations', type=int, default=210000)
    parser.add_argument('--lr', type=float, default=0.0015)
    parser.add_argument('--beta_1', type=float, default=0.0)
    parser.add_argument('--batch_size', type=int, default=5)
    parser.add_argument('--experiment_dir', default=None)
    parser.add_argument('--checkpoint_dir_GAN', default='./checkpoint/stylegan_v2/stylegan2_cat256.pth')
    parser.add_argument('--config_dir', default='./checkpoint/biggan/256/biggan-deep-256-config.json') # BigGAN needs it
    parser.add_argument('--checkpoint_dir_E', default=None)#'./result/StyleGAN1-car512-Aligned-modelV2/models/E_model_iter100000.pth'
    parser.add_argument('--img_size',type=int, default=256)
    parser.add_argument('--img_channels', type=int, default=3)# RGB:3 ,L:1
    parser.add_argument('--z_dim', type=int, default=512) # BigGAN,z=128, PGGAN and StyleGANs = 512
    parser.add_argument('--mtype', type=int, default=2) # StyleGANv1=1, StyleGANv2=2, PGGAN=3, BigGAN00
    parser.add_argument('--start_features', type=int, default=64) # 16->1024 32->512 64->256 
    args = parser.parse_args()
