### ISSUE TITLE
image reconstruction

### ISSUE THREAD

**Issue by JNash123** [disanda/MTV-TSA#4]
how can i use pre-trained model to get image reconstruction directly? what should i do

**Comment by JNash123** [comment]
this? rec_real_img.py

**Comment by disanda** [comment]
Try to run  [embedding_img.py](https://github.com/disanda/DSE/blob/master/embedding_img.py), or [embedding_v2_styleGAN1.py](https://github.com/disanda/DSE/blob/master/embedding_v2_styleGAN1.py).

They use StyleGAN to invert (embed) real face to style latent code (w),  then save w and put to G to reconstruct faces. Other GANs are similar in this way.

**Comment by disanda** [comment]
> this? rec_real_img.py

No, it is a previous script. Just running [embedding_img.py](https://github.com/disanda/DSE/blob/master/embedding_img.py), or [embedding_v2_styleGAN1.py](https://github.com/disanda/DSE/blob/master/embedding_v2_styleGAN1.py) is enough.

**Comment by JNash123** [comment]
> > this? rec_real_img.py
> 
> No, it is a previous script. Just running [embedding_img.py](https://github.com/disanda/DSE/blob/master/embedding_img.py), or [embedding_v2_styleGAN1.py](https://github.com/disanda/DSE/blob/master/embedding_v2_styleGAN1.py) is enough.

okay, thanks, i'll try

**Comment by JNash123** [comment]
> > this? rec_real_img.py
> 
> No, it is a previous script. Just running [embedding_img.py](https://github.com/disanda/DSE/blob/master/embedding_img.py), or [embedding_v2_styleGAN1.py](https://github.com/disanda/DSE/blob/master/embedding_v2_styleGAN1.py) is enough.

sorry, but when i ran embedding_v2_styleGAN2.py, embedding_v2_styleGAN1.py or embedding_img.py, i didn't get anything, it just created a directory.
environment：ubuntu20.04, py3.7, 3090

![1660722697021](https://user-images.githubusercontent.com/29653541/185065970-9ac2e91b-9dbd-487c-969d-df17bc5e7514.jpg)

![1660722728310](https://user-images.githubusercontent.com/29653541/185065978-02bccfb2-6ebe-4aa1-8350-06266c0beefe.jpg)


![1660722753138](https://user-images.githubusercontent.com/29653541/185065990-c6b101bb-b8e9-49d2-b12b-7a0d8d753064.jpg)
