### ISSUE TITLE
about image reconstruction

### ISSUE THREAD

**Issue by JNash123** [disanda/MTV-TSA#5]
i ran embedding_v2_styleGAN2.py, embedding_v2_styleGAN1.py or embedding_img.py, i didn't get anything, it just created a directory.
environment：ubuntu20.04, py3.7, 3090, Can u help me?
![185065970-9ac2e91b-9dbd-487c-969d-df17bc5e7514](https://user-images.githubusercontent.com/29653541/185797680-0bb37088-9ec5-40ac-90ef-e4a6898ada8d.jpg)
![185065978-02bccfb2-6ebe-4aa1-8350-06266c0beefe](https://user-images.githubusercontent.com/29653541/185797706-5a2484b3-2739-4139-9b95-58e19825ce75.jpg)
![185065990-c6b101bb-b8e9-49d2-b12b-7a0d8d753064](https://user-images.githubusercontent.com/29653541/185797713-d0de1d46-64d5-4194-9061-ff627e7533ea.jpg)

**Comment by disanda** [comment]
Maybe I can help, but sometimes it is just a coding ability. I think you can run the code step by step. 

BTW, in the previous, I ran it in the shell (command line, also an Ubuntu server).

Be honest, I do not know why you can not run it. Here are some notes that may help you. "

(1) It should download the pre-trained model file, and put real-face images in the corresponding files. (See lines 200-202)

(2) I think you should double check the train function. In the case of "embedding_v2_styleGAN1.py", the file runs the function: "train(tensor_writer = writer, args = args, imgs_tensor = imgs1)" in the list line (241).

train function loads model and optimizes latent code  (lines 21–136), and saves latent code in the files (e.g., lines 163, 178).

**Comment by JNash123** [comment]
> Maybe I can help, but sometimes it is just a coding ability. I think you can run the code step by step.
> 
> BTW, in the previous, I ran it in the shell (command line, also an Ubuntu server).
> 
> Be honest, I do not know why you can not run it. Here are some notes that may help you. "
> 
> (1) It should download the pre-trained model file, and put real-face images in the corresponding files. (See lines 200-202)
> 
> (2) I think you should double check the train function. In the case of "embedding_v2_styleGAN1.py", the file runs the function: "train(tensor_writer = writer, args = args, imgs_tensor = imgs1)" in the list line (241).
> 
> train function loads model and optimizes latent code (lines 21–136), and saves latent code in the files (e.g., lines 163, 178).

thank u, i'll try again, u're very thoughtful, thank u again
